playwright.yml

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -30,10 +30,18 @@ jobs:
 
       - name: Wait for application to be ready
         run: |
-          until curl -s http://localhost:7777/ | grep "ok"; do
+            timeout=300
+            interval=5
+            elapsed=0
+            until curl -s http://drill-and-practice:7777 | grep "ok"; do
+            if [ "$elapsed" -ge "$timeout" ]; then
+                echo "Application failed to become ready within $timeout seconds."
+                exit 1
+            fi
             echo "Waiting for application..."
-            sleep 5
-          done
+            sleep $interval
+            elapsed=$((elapsed + interval))
+            done
 
       - name: Run Playwright tests
         run: $ docker compose up -d drill-and-practice database && \ 
